name: CI

on:
  push:
    branches: ['main']
  pull_request:
    branches: ['main']
  workflow_call:

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [18.x, 20.x]

    steps:
      - uses: actions/checkout@v4
      - uses: pnpm/action-setup@v3
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'pnpm'
      - run: pnpm i --frozen-lockfile
      - run: pnpm run build
      - run: pnpm run format:check
