on:
  release:
    types: [created]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [18.x, 20.x]

    steps:
      - uses: actions/checkout@v3
      - uses: pnpm/action-setup@v2.4.0
        with:
          version: 7.12.2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'pnpm'
      - run: pnpm i --frozen-lockfile
      - run: pnpm run build
      - run: pnpm run format:check

  publish-npm:
    needs: build
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - uses: pnpm/action-setup@v2.4.0
        with:
          version: 7.12.2
      - uses: actions/setup-node@v3
        with:
          node-version: 18
          cache: 'pnpm'
          registry-url: 'https://registry.npmjs.org'
      - run: pnpm i --frozen-lockfile
      - run: pnpm run build
      - run: pnpm config set //registry.npmjs.org/:_authToken=${{ secrets.NPM_TOKEN }} -L project
      - run: pnpm publish --access public --no-git-checks
